# yaml-language-server: $schema=https://raw.githubusercontent.com/camptocamp/c2cciutils/1.6.10/c2cciutils/schema.json

checks:
  versions: False
  codespell:
    ignore_re:
      - ^CHANGELOG\.md$
      - ^poetry\.lock$

publish:
  docker:
    images: []
    dispatch: false
