name: Auto reviews updates

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_run:
    workflows:
      - None
    types:
      - completed

jobs:
  auto-merge:
    name: Auto reviews updates
    runs-on: ubuntu-22.04
    timeout-minutes: 5

    steps:
      - name: Auto reviews updates
        uses: golfzaptw/action-auto-reviews-from-branches@1.2.3
        with:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          AUTHOR: renovate[bot]
