name: Rebuild

on:
  schedule:
    - cron: '30 2 * * *'

jobs:
  rebuild:
    runs-on: ubuntu-20.04
    name: Rebuild
    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        branch:
          - master

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - run: echo "${HOME}/.local/bin" >> ${GITHUB_PATH}
      - run: python3 -m pip install --user --requirement=ci/requirements.txt

      - name: Checks
        run: c2cciutils-checks

      - run: python3 -m pip install --user --editable .
      - run: python3 -m pip install --user pytest
      - run: pytest
